spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/user_center_vivo?useUnicode=true&characterEncoding=utf-8
    username: kaifa
    password: '{cipher}AQAab3xYLf/pNNg6w2dPdTOIcN0wVa2n7er0K/f1hvalrH4YKeOzWbvF7YYnfV9oQbH4aWvSLw7/ia7/QcZreQvs7h0xnwn/kADz8R5RxNJ9wAXVPIuZHaKdtz2kb5756cWXMbRITtGIDHjs11k8W66H2N27zbAXBHB9Z83dGPrvY4JxfzdO2Hnzt8Mh1s00pzSnxmUEuUO/98SjpnaN8I8pClP9/UXgOM/3RVpFQdU2J1+yv0f5yll1nx5Kq96PW3pRAOZ3oc1Umxt7KAgtXjFdqdEwR/yOQGYhdBJtjuz9UXHEZhC0V7a9TSGhXIUiUt/vdH8Ax+Mk9/+0/ADvBNJUG0xbLvVLiRKkumNxjwh7VrVDcqz5FYW3IKjhI3mqhiE='
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
management:
  endpoints:
    web:
      exposure:
        include: '*'
chujian:
  usercenter:
    hostname: usercenter.ups.firstmeet
    port: 6565
  uid-generator:
    hostname: uidgenerator.ups.firstmeet
    port: 6565
server:
  port: 8080
grpc:
  port: 6565