spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/user_center_huawei?useUnicode=true&characterEncoding=utf-8
    username: kaifa
    password: '{cipher}AQClzkmlBjmU+GAGONO5dE/B0Y+WZa9xjwTnIxOk3u+Kl0nvdco/8dYIXEJNwE97cS95blGWX+4IT/kprkS5txTqAxWUiLk2UL5en3ueO1nllmMdlExpb1YGwBIKpp1A1+tMR086VXYI4W5/n22tz3PNI7Kyh0Or9GI+FvYedTp5WdFB7UJxPPTmwiX8Dfg+l0CfmtemWVwMzRvSTClvworVL1wecCS6Yd/yNShQhFG3EGSlQ6gPmEK5jvzZuQBkwNmMSIxc8Ac5tkiBWGBQgOMohaDWAMoz7DGjeLRVDQ03jlkUW6djq5rQIhRiTGRsv5I4MEO0tYDV5Ar0CmypxOaJpmdWzWu+6FPogqvT+d8aGAoU/iLZY1afQxuz4RJKrso='
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
chujian:
  usercenter:
    hostname: usercenter.ups.firstmeet
    port: 6565
  uid-generator:
    hostname: uidgenerator.ups.firstmeet
    port: 6565
server:
  tomcat:
    accesslog:
      enabled: true
      directory: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/access-log
  port: 8080
grpc:
  port: 6565